from __future__ import annotations

from .models import ConfigField, NodeDefinition, PortDefinition


CATEGORY_COLORS = {
    "Control": "#FFAB19",
    "Input": "#4C97FF",
    "Screen": "#FF6680",
    "Files": "#FFBF00",
    "Logic": "#59C059",
    "Variables": "#FF8C1A",
}

KEY_CHOICES = [
    "enter",
    "space",
    "tab",
    "backspace",
    "delete",
    "esc",
    "up",
    "down",
    "left",
    "right",
    "home",
    "end",
    "pageup",
    "pagedown",
    "shift",
    "ctrl",
    "alt",
    "win",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "f1",
    "f2",
    "f3",
    "f4",
    "f5",
    "f6",
    "f7",
    "f8",
    "f9",
    "f10",
    "f11",
    "f12",
]

MODIFIER_CHOICES = ["", "ctrl", "shift", "alt", "win"]


def build_node_catalog() -> dict[str, NodeDefinition]:
    node_definitions = [
        NodeDefinition(
            type_id="start",
            title="Start",
            category="Control",
            description="Entry point for a macro run.",
            color="#3DD9D6",
            inputs=[],
            outputs=[PortDefinition("next", "Start", "flow", True)],
        ),
        NodeDefinition(
            type_id="delay",
            title="Delay",
            category="Control",
            description="Pause execution for a number of milliseconds.",
            color="#4DA3FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("duration_ms", "Duration", "number", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("duration_ms", "Duration (ms)", "int", 500, minimum=0, maximum=600000, step=50),
            ],
        ),
        NodeDefinition(
            type_id="branch",
            title="Branch",
            category="Control",
            description="Route the flow based on a boolean condition.",
            color="#7EE787",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("condition", "Condition", "boolean", False),
            ],
            outputs=[
                PortDefinition("true_flow", "True", "flow", True),
                PortDefinition("false_flow", "False", "flow", True),
            ],
        ),
        NodeDefinition(
            type_id="if_block",
            title="If",
            category="Control",
            description="Run the nested stack when the condition is true.",
            color="#7EE787",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("condition", "Condition", "boolean", False),
            ],
            outputs=[
                PortDefinition("true_flow", "Then", "flow", True),
                PortDefinition("next", "Next", "flow", True),
            ],
        ),
        NodeDefinition(
            type_id="if_else_block",
            title="If Else",
            category="Control",
            description="Run the Then or Else nested stack based on a condition.",
            color="#7EE787",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("condition", "Condition", "boolean", False),
            ],
            outputs=[
                PortDefinition("true_flow", "Then", "flow", True),
                PortDefinition("false_flow", "Else", "flow", True),
                PortDefinition("next", "Next", "flow", True),
            ],
        ),
        NodeDefinition(
            type_id="repeat_block",
            title="Repeat",
            category="Control",
            description="Run the nested stack a fixed number of times.",
            color="#FFAB19",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("count", "Count", "number", False),
            ],
            outputs=[
                PortDefinition("body", "Do", "flow", True),
                PortDefinition("next", "Next", "flow", True),
            ],
            config_fields=[
                ConfigField("count", "Count", "int", 10, minimum=0, maximum=100000, step=1),
            ],
        ),
        NodeDefinition(
            type_id="repeat_until_block",
            title="Repeat Until",
            category="Control",
            description="Keep running the nested stack until the condition becomes true.",
            color="#FFAB19",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("condition", "Condition", "boolean", False),
            ],
            outputs=[
                PortDefinition("body", "Do", "flow", True),
                PortDefinition("next", "Next", "flow", True),
            ],
        ),
        NodeDefinition(
            type_id="forever_block",
            title="Forever",
            category="Control",
            description="Keep running the nested stack until you stop the macro.",
            color="#FFAB19",
            inputs=[PortDefinition("flow_in", "Run", "flow", False)],
            outputs=[PortDefinition("body", "Do", "flow", True)],
        ),
        NodeDefinition(
            type_id="wait_until",
            title="Wait Until",
            category="Control",
            description="Pause the flow until the condition becomes true.",
            color="#FFAB19",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("condition", "Condition", "boolean", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
        ),
        NodeDefinition(
            type_id="log_text",
            title="Print",
            category="Control",
            description="Print text, numbers, or images to the runtime log.",
            color="#59A5FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("value", "Value", "any", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[ConfigField("value", "Fallback Text", "text", "FlowMacro says hi")],
        ),
        NodeDefinition(
            type_id="number_value",
            title="Number Value",
            category="Values",
            description="Emit a numeric value into the graph.",
            color="#FFB454",
            inputs=[],
            outputs=[PortDefinition("value", "Value", "number", True)],
            config_fields=[ConfigField("value", "Value", "float", 100.0, step=1.0)],
            visible_in_palette=False,
        ),
        NodeDefinition(
            type_id="text_value",
            title="String Value",
            category="Values",
            description="Emit a string value into the graph.",
            color="#59A5FF",
            inputs=[],
            outputs=[PortDefinition("value", "Value", "text", True)],
            config_fields=[ConfigField("value", "Value", "text", "Hello from FlowMacro")],
            visible_in_palette=False,
        ),
        NodeDefinition(
            type_id="boolean_value",
            title="Boolean Value",
            category="Values",
            description="Emit a boolean value into the graph.",
            color="#7EE787",
            inputs=[],
            outputs=[PortDefinition("value", "Value", "boolean", True)],
            config_fields=[ConfigField("value", "Value", "bool", True)],
            visible_in_palette=False,
        ),
        NodeDefinition(
            type_id="get_variable",
            title="Variable",
            category="Variables",
            description="Read the current value stored in a variable.",
            color="#FF8C1A",
            inputs=[PortDefinition("name", "Name", "text", False)],
            outputs=[PortDefinition("value", "Value", "any", True)],
            config_fields=[ConfigField("name", "Name", "text", "score")],
        ),
        NodeDefinition(
            type_id="set_variable",
            title="Set Variable",
            category="Variables",
            description="Store a value in a variable name.",
            color="#FF8C1A",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("name", "Name", "text", False),
                PortDefinition("value", "Value", "any", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("name", "Name", "text", "score"),
                ConfigField("value", "Value", "text", "0"),
            ],
        ),
        NodeDefinition(
            type_id="change_variable",
            title="Change Variable",
            category="Variables",
            description="Add a number to the current variable value.",
            color="#FF8C1A",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("name", "Name", "text", False),
                PortDefinition("amount", "Amount", "number", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("name", "Name", "text", "score"),
                ConfigField("amount", "Amount", "int", 1, step=1),
            ],
        ),
        NodeDefinition(
            type_id="path_value",
            title="Legacy Path String",
            category="Values",
            description="Compatibility node for older projects. Use String Value instead.",
            color="#59A5FF",
            inputs=[],
            outputs=[PortDefinition("value", "Value", "text", True)],
            config_fields=[ConfigField("value", "Value", "text", "captures/capture_{timestamp}.png")],
            visible_in_palette=False,
        ),
        NodeDefinition(
            type_id="math_operation",
            title="Math Operation",
            category="Logic",
            description="Add, subtract, multiply, or divide two numbers.",
            color="#FFB454",
            inputs=[
                PortDefinition("left", "Left", "number", False),
                PortDefinition("right", "Right", "number", False),
            ],
            outputs=[PortDefinition("result", "Result", "number", True)],
            config_fields=[
                ConfigField("left", "Left", "float", 0.0, step=1.0),
                ConfigField("right", "Right", "float", 0.0, step=1.0),
                ConfigField(
                    "operator",
                    "Operator",
                    "choice",
                    "+",
                    choices=["+", "-", "*", "/"],
                ),
            ],
        ),
        NodeDefinition(
            type_id="compare_numbers",
            title="Compare",
            category="Logic",
            description="Compare two numbers and output a boolean result.",
            color="#7EE787",
            inputs=[
                PortDefinition("left", "Left", "number", False),
                PortDefinition("right", "Right", "number", False),
            ],
            outputs=[PortDefinition("result", "Result", "boolean", True)],
            config_fields=[
                ConfigField("left", "Left", "float", 0.0, step=1.0),
                ConfigField("right", "Right", "float", 0.0, step=1.0),
                ConfigField(
                    "operator",
                    "Operator",
                    "choice",
                    ">",
                    choices=[
                        ">",
                        "<",
                        "=",
                        ">=",
                        "<=",
                        "!=",
                    ],
                ),
            ],
        ),
        NodeDefinition(
            type_id="join_text",
            title="Join Strings",
            category="Logic",
            description="Combine two string values with a separator.",
            color="#59A5FF",
            inputs=[
                PortDefinition("first", "First", "text", False),
                PortDefinition("second", "Second", "text", False),
            ],
            outputs=[PortDefinition("result", "Result", "text", True)],
            config_fields=[
                ConfigField("first", "First", "text", "Flow"),
                ConfigField("second", "Second", "text", "Macro"),
                ConfigField("separator", "Separator", "text", " "),
            ],
        ),
        NodeDefinition(
            type_id="replace_text",
            title="Replace Text",
            category="Logic",
            description="Replace part of a string with new text.",
            color="#59A5FF",
            inputs=[
                PortDefinition("source", "Source", "text", False),
                PortDefinition("find", "Find", "text", False),
                PortDefinition("replace", "Replace", "text", False),
            ],
            outputs=[PortDefinition("result", "Result", "text", True)],
            config_fields=[
                ConfigField("source", "Source", "text", "FlowMacro Studio"),
                ConfigField("find", "Find", "text", "Studio"),
                ConfigField("replace", "Replace", "text", "Runner"),
            ],
        ),
        NodeDefinition(
            type_id="text_contains",
            title="Text Contains",
            category="Logic",
            description="Check whether one string contains another.",
            color="#7EE787",
            inputs=[
                PortDefinition("source", "Source", "text", False),
                PortDefinition("search", "Search", "text", False),
            ],
            outputs=[PortDefinition("result", "Result", "boolean", True)],
            config_fields=[
                ConfigField("source", "Source", "text", "FlowMacro Studio"),
                ConfigField("search", "Search", "text", "Macro"),
            ],
        ),
        NodeDefinition(
            type_id="boolean_not",
            title="Not",
            category="Logic",
            description="Invert a boolean value.",
            color="#7EE787",
            inputs=[PortDefinition("value", "Value", "boolean", False)],
            outputs=[PortDefinition("result", "Result", "boolean", True)],
            config_fields=[ConfigField("value", "Value", "bool", False)],
        ),
        NodeDefinition(
            type_id="boolean_and",
            title="And",
            category="Logic",
            description="Return true only when both boolean inputs are true.",
            color="#7EE787",
            inputs=[
                PortDefinition("left", "Left", "boolean", False),
                PortDefinition("right", "Right", "boolean", False),
            ],
            outputs=[PortDefinition("result", "Result", "boolean", True)],
            config_fields=[
                ConfigField("left", "Left", "bool", True),
                ConfigField("right", "Right", "bool", True),
            ],
        ),
        NodeDefinition(
            type_id="boolean_or",
            title="Or",
            category="Logic",
            description="Return true when either boolean input is true.",
            color="#7EE787",
            inputs=[
                PortDefinition("left", "Left", "boolean", False),
                PortDefinition("right", "Right", "boolean", False),
            ],
            outputs=[PortDefinition("result", "Result", "boolean", True)],
            config_fields=[
                ConfigField("left", "Left", "bool", False),
                ConfigField("right", "Right", "bool", False),
            ],
        ),
        NodeDefinition(
            type_id="get_files",
            title="Get Files",
            category="Files",
            description="Collect files from a folder with a glob pattern.",
            color="#FFD166",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("folder", "Folder", "text", False),
                PortDefinition("pattern", "Pattern", "text", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("files", "Files", "files", True),
            ],
            config_fields=[
                ConfigField("folder", "Folder", "text", "."),
                ConfigField("pattern", "Pattern", "text", "*.*"),
            ],
        ),
        NodeDefinition(
            type_id="files_count",
            title="Files Count",
            category="Files",
            description="Count the number of files in a files list.",
            color="#FFD166",
            inputs=[PortDefinition("files", "Files", "files", False)],
            outputs=[PortDefinition("count", "Count", "number", True)],
        ),
        NodeDefinition(
            type_id="first_file",
            title="Get File",
            category="Files",
            description="Take the first full file path from a files list.",
            color="#59A5FF",
            inputs=[PortDefinition("files", "Files", "files", False)],
            outputs=[PortDefinition("path", "Path", "text", True)],
        ),
        NodeDefinition(
            type_id="file_exists",
            title="File Exists",
            category="Files",
            description="Check whether a file or folder exists.",
            color="#7EE787",
            inputs=[PortDefinition("path", "Path", "text", False)],
            outputs=[PortDefinition("exists", "Exists", "boolean", True)],
            config_fields=[ConfigField("path", "Path", "text", ".")],
        ),
        NodeDefinition(
            type_id="read_text_file",
            title="Read Text File",
            category="Files",
            description="Read a text file into a string value.",
            color="#59A5FF",
            inputs=[PortDefinition("path", "Path", "text", False)],
            outputs=[PortDefinition("text", "Text", "text", True)],
            config_fields=[ConfigField("path", "Path", "text", "notes.txt")],
        ),
        NodeDefinition(
            type_id="write_text_file",
            title="Write Text File",
            category="Files",
            description="Write text to a file, with overwrite or append mode.",
            color="#59A5FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("path", "Path", "text", False),
                PortDefinition("text", "Text", "text", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("saved_path", "Saved Path", "text", True),
            ],
            config_fields=[
                ConfigField("path", "Path", "text", "output.txt"),
                ConfigField("text", "Text", "text", "Hello from FlowMacro"),
                ConfigField("mode", "Mode", "choice", "overwrite", choices=["overwrite", "append"]),
            ],
        ),
        NodeDefinition(
            type_id="delete_file",
            title="Delete File",
            category="Files",
            description="Delete a file from disk.",
            color="#FF7B72",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("path", "Path", "text", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("deleted", "Deleted", "boolean", True),
            ],
            config_fields=[
                ConfigField("path", "Path", "text", "output.txt"),
                ConfigField("missing_ok", "Missing OK", "bool", True),
            ],
        ),
        NodeDefinition(
            type_id="copy_file",
            title="Copy File",
            category="Files",
            description="Copy a file to a new location.",
            color="#FFD166",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("source", "Source", "text", False),
                PortDefinition("destination", "Destination", "text", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("saved_path", "Saved Path", "text", True),
            ],
            config_fields=[
                ConfigField("source", "Source", "text", "input.txt"),
                ConfigField("destination", "Destination", "text", "copy.txt"),
                ConfigField("overwrite", "Overwrite", "bool", True),
            ],
        ),
        NodeDefinition(
            type_id="move_file",
            title="Move File",
            category="Files",
            description="Move a file to a new location.",
            color="#FFD166",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("source", "Source", "text", False),
                PortDefinition("destination", "Destination", "text", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("saved_path", "Saved Path", "text", True),
            ],
            config_fields=[
                ConfigField("source", "Source", "text", "input.txt"),
                ConfigField("destination", "Destination", "text", "moved.txt"),
                ConfigField("overwrite", "Overwrite", "bool", True),
            ],
        ),
        NodeDefinition(
            type_id="path_join",
            title="Join Path",
            category="Files",
            description="Combine a folder path and name into one path string.",
            color="#59A5FF",
            inputs=[
                PortDefinition("folder", "Folder", "text", False),
                PortDefinition("name", "Name", "text", False),
            ],
            outputs=[PortDefinition("path", "Path", "text", True)],
            config_fields=[
                ConfigField("folder", "Folder", "text", "."),
                ConfigField("name", "Name", "text", "output.txt"),
            ],
        ),
        NodeDefinition(
            type_id="file_name",
            title="Get File Name",
            category="Files",
            description="Return the file name part of a path.",
            color="#59A5FF",
            inputs=[PortDefinition("path", "Path", "text", False)],
            outputs=[PortDefinition("name", "Name", "text", True)],
            config_fields=[ConfigField("path", "Path", "text", "captures/capture.png")],
        ),
        NodeDefinition(
            type_id="take_screenshot",
            title="Take Screenshot",
            category="Screen",
            description="Capture the current screen and return it as an image value.",
            color="#FF7AA2",
            inputs=[],
            outputs=[PortDefinition("image", "Image", "image", True)],
        ),
        NodeDefinition(
            type_id="set_stage",
            title="Set Stage",
            category="Screen",
            description="Show an image in the stage preview.",
            color="#FF7AA2",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("image", "Image", "image", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
        ),
        NodeDefinition(
            type_id="crop_image",
            title="Crop Image",
            category="Screen",
            description="Crop an input image and return a new image.",
            color="#D78EFF",
            inputs=[
                PortDefinition("image", "Image", "image", False),
                PortDefinition("x", "X", "number", False),
                PortDefinition("y", "Y", "number", False),
                PortDefinition("width", "Width", "number", False),
                PortDefinition("height", "Height", "number", False),
            ],
            outputs=[PortDefinition("image", "Image", "image", True)],
            config_fields=[
                ConfigField("x", "X", "int", 0, minimum=0, maximum=10000, step=1),
                ConfigField("y", "Y", "int", 0, minimum=0, maximum=10000, step=1),
                ConfigField("width", "Width", "int", 100, minimum=1, maximum=10000, step=1),
                ConfigField("height", "Height", "int", 100, minimum=1, maximum=10000, step=1),
            ],
        ),
        NodeDefinition(
            type_id="set_image_pixel",
            title="Set Image Pixel",
            category="Screen",
            description="Set one pixel in an image and return a new image.",
            color="#D78EFF",
            inputs=[
                PortDefinition("image", "Image", "image", False),
                PortDefinition("x", "X", "number", False),
                PortDefinition("y", "Y", "number", False),
                PortDefinition("red", "Red", "number", False),
                PortDefinition("green", "Green", "number", False),
                PortDefinition("blue", "Blue", "number", False),
            ],
            outputs=[PortDefinition("image", "Image", "image", True)],
            config_fields=[
                ConfigField("x", "X", "int", 0, minimum=0, maximum=10000, step=1),
                ConfigField("y", "Y", "int", 0, minimum=0, maximum=10000, step=1),
                ConfigField("red", "Red", "int", 255, minimum=0, maximum=255, step=1),
                ConfigField("green", "Green", "int", 255, minimum=0, maximum=255, step=1),
                ConfigField("blue", "Blue", "int", 255, minimum=0, maximum=255, step=1),
            ],
        ),
        NodeDefinition(
            type_id="get_pixel",
            title="Get Pixel from Screen",
            category="Screen",
            description="Sample the RGB color of a live screen pixel.",
            color="#FF7B72",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("x", "X", "number", False),
                PortDefinition("y", "Y", "number", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("pixel", "Pixel", "pixel", True),
                PortDefinition("red", "Red", "number", True),
                PortDefinition("green", "Green", "number", True),
                PortDefinition("blue", "Blue", "number", True),
            ],
            config_fields=[
                ConfigField("x", "X", "int", 100, minimum=0, maximum=10000, step=1),
                ConfigField("y", "Y", "int", 100, minimum=0, maximum=10000, step=1),
            ],
        ),
        NodeDefinition(
            type_id="get_pixel_from_image",
            title="Get Pixel from Image",
            category="Screen",
            description="Read a pixel from an input image.",
            color="#D78EFF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("image", "Image", "image", False),
                PortDefinition("x", "X", "number", False),
                PortDefinition("y", "Y", "number", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("pixel", "Pixel", "pixel", True),
                PortDefinition("red", "Red", "number", True),
                PortDefinition("green", "Green", "number", True),
                PortDefinition("blue", "Blue", "number", True),
            ],
            config_fields=[
                ConfigField("x", "X", "int", 100, minimum=0, maximum=10000, step=1),
                ConfigField("y", "Y", "int", 100, minimum=0, maximum=10000, step=1),
            ],
        ),
        NodeDefinition(
            type_id="mouse_move",
            title="Mouse Move",
            category="Input",
            description="Move the mouse pointer to a screen coordinate.",
            color="#4DA3FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("x", "X", "number", False),
                PortDefinition("y", "Y", "number", False),
                PortDefinition("duration_ms", "Duration", "number", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("x", "X", "int", 500, minimum=0, maximum=10000, step=1),
                ConfigField("y", "Y", "int", 500, minimum=0, maximum=10000, step=1),
                ConfigField("duration_ms", "Duration (ms)", "int", 100, minimum=0, maximum=60000, step=25),
            ],
        ),
        NodeDefinition(
            type_id="mouse_click",
            title="Mouse Click",
            category="Input",
            description="Click a mouse button one or more times.",
            color="#FFB454",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("button", "Button", "text", False),
                PortDefinition("clicks", "Clicks", "number", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("button", "Button", "choice", "left", choices=["left", "right", "middle"]),
                ConfigField("clicks", "Clicks", "int", 1, minimum=1, maximum=10, step=1),
            ],
        ),
        NodeDefinition(
            type_id="press_key",
            title="Press Key",
            category="Input",
            description="Press a single keyboard key.",
            color="#59A5FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("key", "Key", "text", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[ConfigField("key", "Key", "choice", "enter", choices=KEY_CHOICES)],
        ),
        NodeDefinition(
            type_id="press_key_combo",
            title="Press Key Combo",
            category="Input",
            description="Press a modifier combo like Ctrl+Shift+S.",
            color="#59A5FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("modifier_1", "Modifier 1", "choice", "ctrl", choices=MODIFIER_CHOICES),
                ConfigField("modifier_2", "Modifier 2", "choice", "", choices=MODIFIER_CHOICES),
                ConfigField("key", "Key", "choice", "s", choices=KEY_CHOICES),
            ],
        ),
        NodeDefinition(
            type_id="hold_key",
            title="Hold Key",
            category="Input",
            description="Start holding a keyboard key until released.",
            color="#59A5FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[ConfigField("key", "Key", "choice", "shift", choices=KEY_CHOICES)],
        ),
        NodeDefinition(
            type_id="release_key",
            title="Release Key",
            category="Input",
            description="Stop holding a previously held keyboard key.",
            color="#59A5FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[ConfigField("key", "Key", "choice", "shift", choices=KEY_CHOICES)],
        ),
        NodeDefinition(
            type_id="type_text",
            title="Type Text",
            category="Input",
            description="Type a text value using the keyboard.",
            color="#59A5FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("text", "Text", "text", False),
                PortDefinition("interval_ms", "Interval", "number", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("text", "Text", "text", "FlowMacro Studio"),
                ConfigField("interval_ms", "Interval (ms)", "int", 0, minimum=0, maximum=5000, step=10),
            ],
        ),
    ]
    for node in node_definitions:
        node.color = CATEGORY_COLORS.get(node.category, node.color)
    return {node.type_id: node for node in node_definitions}
