from __future__ import annotations

from .models import ConfigField, NodeDefinition, PortDefinition


def build_node_catalog() -> dict[str, NodeDefinition]:
    node_definitions = [
        NodeDefinition(
            type_id="start",
            title="Start",
            category="Control",
            description="Entry point for a macro run.",
            color="#3DD9D6",
            inputs=[],
            outputs=[PortDefinition("next", "Start", "flow", True)],
        ),
        NodeDefinition(
            type_id="delay",
            title="Delay",
            category="Control",
            description="Pause execution for a number of milliseconds.",
            color="#4DA3FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("duration_ms", "Duration", "number", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("duration_ms", "Duration (ms)", "int", 500, minimum=0, maximum=600000, step=50),
            ],
        ),
        NodeDefinition(
            type_id="branch",
            title="Branch",
            category="Control",
            description="Route the flow based on a boolean condition.",
            color="#7EE787",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("condition", "Condition", "boolean", False),
            ],
            outputs=[
                PortDefinition("true_flow", "True", "flow", True),
                PortDefinition("false_flow", "False", "flow", True),
            ],
        ),
        NodeDefinition(
            type_id="log_text",
            title="Print",
            category="Control",
            description="Print text, numbers, or images to the runtime log.",
            color="#59A5FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("value", "Value", "any", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[ConfigField("value", "Fallback Text", "text", "FlowMacro says hi")],
        ),
        NodeDefinition(
            type_id="number_value",
            title="Number Value",
            category="Values",
            description="Emit a numeric value into the graph.",
            color="#FFB454",
            inputs=[],
            outputs=[PortDefinition("value", "Value", "number", True)],
            config_fields=[ConfigField("value", "Value", "float", 100.0, step=1.0)],
        ),
        NodeDefinition(
            type_id="text_value",
            title="String Value",
            category="Values",
            description="Emit a string value into the graph.",
            color="#59A5FF",
            inputs=[],
            outputs=[PortDefinition("value", "Value", "text", True)],
            config_fields=[ConfigField("value", "Value", "text", "Hello from FlowMacro")],
        ),
        NodeDefinition(
            type_id="boolean_value",
            title="Boolean Value",
            category="Values",
            description="Emit a boolean value into the graph.",
            color="#7EE787",
            inputs=[],
            outputs=[PortDefinition("value", "Value", "boolean", True)],
            config_fields=[ConfigField("value", "Value", "bool", True)],
        ),
        NodeDefinition(
            type_id="path_value",
            title="Legacy Path String",
            category="Values",
            description="Compatibility node for older projects. Use String Value instead.",
            color="#59A5FF",
            inputs=[],
            outputs=[PortDefinition("value", "Value", "text", True)],
            config_fields=[ConfigField("value", "Value", "text", "captures/capture_{timestamp}.png")],
            visible_in_palette=False,
        ),
        NodeDefinition(
            type_id="math_operation",
            title="Math Operation",
            category="Logic",
            description="Add, subtract, multiply, or divide two numbers.",
            color="#FFB454",
            inputs=[
                PortDefinition("left", "Left", "number", False),
                PortDefinition("right", "Right", "number", False),
            ],
            outputs=[PortDefinition("result", "Result", "number", True)],
            config_fields=[
                ConfigField("left", "Left", "float", 0.0, step=1.0),
                ConfigField("right", "Right", "float", 0.0, step=1.0),
                ConfigField(
                    "operator",
                    "Operator",
                    "choice",
                    "add",
                    choices=["add", "subtract", "multiply", "divide"],
                ),
            ],
        ),
        NodeDefinition(
            type_id="compare_numbers",
            title="Compare Numbers",
            category="Logic",
            description="Compare two numbers and output a boolean result.",
            color="#7EE787",
            inputs=[
                PortDefinition("left", "Left", "number", False),
                PortDefinition("right", "Right", "number", False),
            ],
            outputs=[PortDefinition("result", "Result", "boolean", True)],
            config_fields=[
                ConfigField("left", "Left", "float", 0.0, step=1.0),
                ConfigField("right", "Right", "float", 0.0, step=1.0),
                ConfigField(
                    "operator",
                    "Operator",
                    "choice",
                    "greater_than",
                    choices=[
                        "greater_than",
                        "greater_or_equal",
                        "equal",
                        "less_or_equal",
                        "less_than",
                        "not_equal",
                    ],
                ),
            ],
        ),
        NodeDefinition(
            type_id="join_text",
            title="Join Strings",
            category="Logic",
            description="Combine two string values with a separator.",
            color="#59A5FF",
            inputs=[
                PortDefinition("first", "First", "text", False),
                PortDefinition("second", "Second", "text", False),
            ],
            outputs=[PortDefinition("result", "Result", "text", True)],
            config_fields=[
                ConfigField("first", "First", "text", "Flow"),
                ConfigField("second", "Second", "text", "Macro"),
                ConfigField("separator", "Separator", "text", " "),
            ],
        ),
        NodeDefinition(
            type_id="get_files",
            title="Get Files",
            category="Files",
            description="Collect files from a folder with a glob pattern.",
            color="#FFD166",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("folder", "Folder", "text", False),
                PortDefinition("pattern", "Pattern", "text", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("files", "Files", "files", True),
            ],
            config_fields=[
                ConfigField("folder", "Folder", "text", "."),
                ConfigField("pattern", "Pattern", "text", "*.*"),
            ],
        ),
        NodeDefinition(
            type_id="files_count",
            title="Files Count",
            category="Files",
            description="Count the number of files in a files list.",
            color="#FFD166",
            inputs=[PortDefinition("files", "Files", "files", False)],
            outputs=[PortDefinition("count", "Count", "number", True)],
        ),
        NodeDefinition(
            type_id="first_file",
            title="Get File",
            category="Files",
            description="Take the first full file path from a files list.",
            color="#59A5FF",
            inputs=[PortDefinition("files", "Files", "files", False)],
            outputs=[PortDefinition("path", "Path", "text", True)],
        ),
        NodeDefinition(
            type_id="file_exists",
            title="File Exists",
            category="Files",
            description="Check whether a file or folder exists.",
            color="#7EE787",
            inputs=[PortDefinition("path", "Path", "text", False)],
            outputs=[PortDefinition("exists", "Exists", "boolean", True)],
            config_fields=[ConfigField("path", "Path", "text", ".")],
        ),
        NodeDefinition(
            type_id="take_screenshot",
            title="Take Screenshot",
            category="Screen",
            description="Capture the current screen and save it to disk.",
            color="#FF7AA2",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("file_path", "File Path", "text", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("saved_path", "Saved Path", "text", True),
                PortDefinition("image", "Image", "image", True),
            ],
            config_fields=[
                ConfigField("file_path", "File Path", "text", "captures/capture_{timestamp}.png"),
            ],
        ),
        NodeDefinition(
            type_id="get_pixel",
            title="Get Pixel from Screen",
            category="Screen",
            description="Sample the RGB color of a live screen pixel.",
            color="#FF7B72",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("x", "X", "number", False),
                PortDefinition("y", "Y", "number", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("pixel", "Pixel", "pixel", True),
                PortDefinition("red", "Red", "number", True),
                PortDefinition("green", "Green", "number", True),
                PortDefinition("blue", "Blue", "number", True),
            ],
            config_fields=[
                ConfigField("x", "X", "int", 100, minimum=0, maximum=10000, step=1),
                ConfigField("y", "Y", "int", 100, minimum=0, maximum=10000, step=1),
            ],
        ),
        NodeDefinition(
            type_id="get_pixel_from_image",
            title="Get Pixel from Image",
            category="Screen",
            description="Read a pixel from a screenshot image or a file path.",
            color="#D78EFF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("image", "Image", "image", False),
                PortDefinition("file_path", "File Path", "text", False),
                PortDefinition("x", "X", "number", False),
                PortDefinition("y", "Y", "number", False),
            ],
            outputs=[
                PortDefinition("next", "Next", "flow", True),
                PortDefinition("pixel", "Pixel", "pixel", True),
                PortDefinition("red", "Red", "number", True),
                PortDefinition("green", "Green", "number", True),
                PortDefinition("blue", "Blue", "number", True),
            ],
            config_fields=[
                ConfigField("file_path", "File Path", "text", ""),
                ConfigField("x", "X", "int", 100, minimum=0, maximum=10000, step=1),
                ConfigField("y", "Y", "int", 100, minimum=0, maximum=10000, step=1),
            ],
        ),
        NodeDefinition(
            type_id="mouse_move",
            title="Mouse Move",
            category="Input",
            description="Move the mouse pointer to a screen coordinate.",
            color="#4DA3FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("x", "X", "number", False),
                PortDefinition("y", "Y", "number", False),
                PortDefinition("duration_ms", "Duration", "number", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("x", "X", "int", 500, minimum=0, maximum=10000, step=1),
                ConfigField("y", "Y", "int", 500, minimum=0, maximum=10000, step=1),
                ConfigField("duration_ms", "Duration (ms)", "int", 100, minimum=0, maximum=60000, step=25),
            ],
        ),
        NodeDefinition(
            type_id="mouse_click",
            title="Mouse Click",
            category="Input",
            description="Click a mouse button one or more times.",
            color="#FFB454",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("button", "Button", "text", False),
                PortDefinition("clicks", "Clicks", "number", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("button", "Button", "choice", "left", choices=["left", "right", "middle"]),
                ConfigField("clicks", "Clicks", "int", 1, minimum=1, maximum=10, step=1),
            ],
        ),
        NodeDefinition(
            type_id="press_key",
            title="Press Key",
            category="Input",
            description="Press a single keyboard key.",
            color="#59A5FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("key", "Key", "text", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[ConfigField("key", "Key", "text", "enter")],
        ),
        NodeDefinition(
            type_id="type_text",
            title="Type Text",
            category="Input",
            description="Type a text value using the keyboard.",
            color="#59A5FF",
            inputs=[
                PortDefinition("flow_in", "Run", "flow", False),
                PortDefinition("text", "Text", "text", False),
                PortDefinition("interval_ms", "Interval", "number", False),
            ],
            outputs=[PortDefinition("next", "Next", "flow", True)],
            config_fields=[
                ConfigField("text", "Text", "text", "FlowMacro Studio"),
                ConfigField("interval_ms", "Interval (ms)", "int", 0, minimum=0, maximum=5000, step=10),
            ],
        ),
    ]
    return {node.type_id: node for node in node_definitions}
